apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: karsajobs-ns
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==