apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: karsajobs-ns
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:4.2.8
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: mongo-credentials
          mountPath: /etc/mongo-credentials
        - name: mongo-config
          mountPath: /config
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-credentials
        secret:
          secretName: mongo-credentials
          items:
          - key: MONGO_ROOT_USERNAME
            path: MONGO_ROOT_USERNAME
          - key: MONGO_ROOT_PASSWORD
            path: MONGO_ROOT_PASSWORD
      - name: mongo-config
        configMap:
          name: mongo-configmap
          items:
          - key: mongo.conf
            path: mongo.conf