apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  namespace: karsajobs-ns
  labels:
    app: karsajobs
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    tier: app
  type: NodePort